services:
  db:
    image: postgres:latest
    container_name: postgres-db-job-offer
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: JOB_OFFER
    ports:
      - "5432:5432"
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - postgres-net
    restart: always

  activemq-artemis:
    image: apache/activemq-artemis:latest
    container_name: activemq-artemis-job-offer
    ports:
      - "61616:61616"  # Puerto JMS
      - "8161:8161"    # Consola web
    environment:
      ARTEMIS_USER: admin
      ARTEMIS_PASSWORD: admin

networks:
  postgres-net:
    driver: bridge