server:
  port: 8081
spring:
  application:
    name: mic-joboffer
  mvc:
    servlet:
      path: /job-offer
  datasource:
    url: jdbc:postgresql://localhost:5432/JOB_OFFER
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    #show-sql: true
    format_sql: true
    properties:
      hibernate:
        format_sql: true

  jms:
    broker-url: ${SPRING_JMS_BROKER_URL}
    user: ${SPRING_JMS_USER}
    password: ${SPRING_JMS_PASSWORD}
producer:
  event:
    host: localhost
    port: 6612
    user: admin
    password: admin
  topic:
    name: job-offer.candidate
consumer:
  event:
    host: localhost
    port: 6613
    user: admin
    password: admin
  topic:
    name: aiintegrations.processed-asset
  subscription:
    name: job-offers
