server:
  port: 8081
spring:
  data:
    rest:
      base-path: /none
      detection-strategy: annotated
  application:
    name: mic-joboffer
  mvc:
    servlet:
      path: /job-offer
  datasource:
    url: jdbc:postgresql://joboffer.postgres.database.azure.com:5432/postgres
    username: antharosadmin
    password: "@passw0rd"
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    #show-sql: true
    format_sql: true
    properties:
      hibernate:
        format_sql: true

  jms:
    broker-url: ${SPRING_JMS_BROKER_URL}
    user: ${SPRING_JMS_USER}
    password: ${SPRING_JMS_PASSWORD}
producer:
  event:
    host: antharos.servicebus.windows.net
    port: 6616
    user: RootManageSharedAccessKey
    password: "/wMNU/hS3WDsPAxtZiJs9oiA8aqRaElaY+ASbL0sHC0="
  topic:
    name: job-offer
consumer:
  event:
    host: antharos.servicebus.windows.net
    port: 6616
    user: RootManageSharedAccessKey
    password: "/wMNU/hS3WDsPAxtZiJs9oiA8aqRaElaY+ASbL0sHC0="
  topic:
    name: aiintegrations
  subscription:
    name: joboffer
security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000 # 1h in millisecond