spring:
  datasource:
    url: jdbc:postgresql://joboffer.postgres.database.azure.com:5432/postgres
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
producer:
  event:
    connection-string: ${EVENT_CONNECTION_STRING}
  topic:
    name: joboffer
consumer:
  event:
    connection-string: ${EVENT_CONNECTION_STRING}
  topic:
    name: aiintegrations
  subscription:
    name: joboffer