spring:
  datasource:
    url: jdbc:postgresql://joboffer.postgres.database.azure.com:5432/postgres
    username: antharosadmin
    password: "@passw0rd"
producer:
  event:
    connection-string: Endpoint=sb://antharos.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=/wMNU/hS3WDsPAxtZiJs9oiA8aqRaElaY+ASbL0sHC0=
  topic:
    name: joboffer
consumer:
  event:
    connection-string: Endpoint=sb://antharos.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=/wMNU/hS3WDsPAxtZiJs9oiA8aqRaElaY+ASbL0sHC0=
  topic:
    name: aiintegrations
  subscription:
    name: joboffer